# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-23 20:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Isoform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MainTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_no', models.IntegerField()),
                ('organism', models.CharField(max_length=200)),
                ('acc_num', models.CharField(max_length=200)),
                ('seq', models.CharField(max_length=200)),
                ('mRNA', models.TextField()),
                ('geneID', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='isoform',
            name='s_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UGP.MainTable'),
        ),
    ]
