# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-23 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UGP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintable',
            name='prot_acc',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maintable',
            name='prot_prod',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
