# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-31 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UGP', '0002_auto_20160324_0234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='isoform',
            name='id',
        ),
        migrations.AddField(
            model_name='isoform',
            name='mRNA_acc',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AddField(
            model_name='isoform',
            name='mRNA_name',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='isoform',
            name='prot_name',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='isoform',
            name='prot_seq',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='isoform',
            name='startcodon',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AddField(
            model_name='isoform',
            name='upstreamATG_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maintable',
            name='foreign_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UGP.Isoform'),
        ),
        migrations.AlterField(
            model_name='isoform',
            name='s_no',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
