# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-31 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UGP', '0003_auto_20160331_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='isoform',
            name='geneID',
            field=models.CharField(default='-', max_length=200),
        ),
    ]
