# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-02 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UGP', '0004_isoform_geneid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintable',
            name='foreign_key',
        ),
        migrations.RemoveField(
            model_name='maintable',
            name='mRNA',
        ),
        migrations.RemoveField(
            model_name='maintable',
            name='prot_prod',
        ),
        migrations.RemoveField(
            model_name='maintable',
            name='seq',
        ),
        migrations.AddField(
            model_name='maintable',
            name='prot_name',
            field=models.TextField(default='-'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maintable',
            name='startcodon',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AddField(
            model_name='maintable',
            name='status',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AddField(
            model_name='maintable',
            name='upstreamATG_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='maintable',
            name='acc_num',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AlterField(
            model_name='maintable',
            name='geneID',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AlterField(
            model_name='maintable',
            name='organism',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AlterField(
            model_name='maintable',
            name='prot_acc',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.DeleteModel(
            name='Isoform',
        ),
    ]
