# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-02 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UGP', '0005_auto_20160402_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintable',
            name='mRNAfastalink',
            field=models.CharField(default='-', max_length=1000),
        ),
    ]
