# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UGP', '0006_maintable_mrnafastalink'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintable',
            name='description',
            field=models.TextField(default='-'),
            preserve_default=False,
        ),
    ]
