# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UGP', '0007_maintable_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintable',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
