# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UGP', '0008_auto_20160423_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintable',
            name='description',
            field=models.TextField(default=b'-'),
        ),
    ]
