# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-15 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UGP', '0010_auto_20160423_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='BacteriaTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chrom_acc_num', models.CharField(default=b'-', max_length=200)),
                ('organism', models.CharField(default=b'-', max_length=200)),
                ('CDSstart', models.IntegerField()),
                ('CDSend', models.IntegerField()),
                ('strand', models.IntegerField()),
                ('startcodon', models.CharField(default=b'-', max_length=200)),
                ('prot_acc', models.CharField(default=b'-', max_length=200)),
                ('prot_description', models.TextField(blank=True, default=b'-', null=True)),
                ('locus_tag', models.CharField(default=b'-', max_length=200)),
                ('sequence', models.TextField(blank=True, default=b'-', null=True)),
            ],
        ),
    ]
