# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-03 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UGP', '0012_archaeatable'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchaeaTable_new',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SwissProtID', models.TextField(blank=True, default=b'-', null=True)),
                ('SwissProtAccID', models.TextField(blank=True, default=b'-', null=True)),
                ('ProtName', models.TextField(blank=True, default=b'-', null=True)),
                ('Organism', models.TextField(blank=True, default=b'-', null=True)),
                ('ProtFunc', models.TextField(blank=True, default=b'-', null=True)),
                ('GenAcc_GenID', models.TextField(blank=True, default=b'-', null=True)),
                ('ProtAcc_ProtID', models.TextField(blank=True, default=b'-', null=True)),
                ('ProtDesc', models.TextField(blank=True, default=b'-', null=True)),
                ('Codon', models.TextField(blank=True, default=b'-', null=True)),
                ('Start', models.IntegerField()),
                ('Stop', models.IntegerField()),
                ('Strand', models.IntegerField()),
                ('MolFunc', models.TextField(blank=True, default=b'-', null=True)),
                ('BioProc', models.TextField(blank=True, default=b'-', null=True)),
                ('CellComp', models.TextField(blank=True, default=b'-', null=True)),
                ('PDB_ID', models.TextField(blank=True, default=b'-', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArchaeaTableNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SwissProtID', models.TextField(blank=True, default=b'-', null=True)),
                ('SwissProtAccID', models.TextField(blank=True, default=b'-', null=True)),
                ('ProtName', models.TextField(blank=True, default=b'-', null=True)),
                ('Organism', models.TextField(blank=True, default=b'-', null=True)),
                ('ProtFunc', models.TextField(blank=True, default=b'-', null=True)),
                ('GenAcc_GenID', models.TextField(blank=True, default=b'-', null=True)),
                ('ProtAcc_ProtID', models.TextField(blank=True, default=b'-', null=True)),
                ('ProtDesc', models.TextField(blank=True, default=b'-', null=True)),
                ('Codon', models.TextField(blank=True, default=b'-', null=True)),
                ('Start', models.IntegerField()),
                ('Stop', models.IntegerField()),
                ('Strand', models.IntegerField()),
                ('MolFunc', models.TextField(blank=True, default=b'-', null=True)),
                ('BioProc', models.TextField(blank=True, default=b'-', null=True)),
                ('CellComp', models.TextField(blank=True, default=b'-', null=True)),
                ('PDB_ID', models.TextField(blank=True, default=b'-', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArchaeaTableNew1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SwissProtID', models.TextField(blank=True, default=b'-', null=True)),
                ('SwissProtAccID', models.TextField(blank=True, default=b'-', null=True)),
                ('ProtName', models.TextField(blank=True, default=b'-', null=True)),
                ('Organism', models.TextField(blank=True, default=b'-', null=True)),
                ('ProtFunc', models.TextField(blank=True, default=b'-', null=True)),
                ('GenAcc_GenID', models.TextField(blank=True, default=b'-', null=True)),
                ('ProtAcc_ProtID', models.TextField(blank=True, default=b'-', null=True)),
                ('ProtDesc', models.TextField(blank=True, default=b'-', null=True)),
                ('Codon', models.TextField(blank=True, default=b'-', null=True)),
                ('Start', models.IntegerField()),
                ('Stop', models.IntegerField()),
                ('Strand', models.IntegerField()),
                ('MolFunc', models.TextField(blank=True, default=b'-', null=True)),
                ('BioProc', models.TextField(blank=True, default=b'-', null=True)),
                ('CellComp', models.TextField(blank=True, default=b'-', null=True)),
                ('PDB_ID', models.TextField(blank=True, default=b'-', null=True)),
            ],
        ),
    ]
