# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-03 20:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UGP', '0013_archaeatable_new_archaeatablenew_archaeatablenew1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArchaeaTable',
        ),
        migrations.DeleteModel(
            name='ArchaeaTable_new',
        ),
        migrations.DeleteModel(
            name='ArchaeaTableNew',
        ),
    ]
