# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UGP', '0017_auto_20170628_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='EukaryotesTableNew2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GeneID', models.TextField(blank=True, default=b'-', null=True)),
                ('Refseq_mRNA_ID', models.TextField(blank=True, default=b'-', null=True)),
                ('Refseq_protein_ID', models.TextField(blank=True, default=b'-', null=True)),
                ('Organism', models.TextField(blank=True, default=b'-', null=True)),
                ('Gene_name', models.TextField(blank=True, default=b'-', null=True)),
                ('Gene_description', models.TextField(blank=True, default=b'-', null=True)),
                ('Protein_description', models.TextField(blank=True, default=b'-', null=True)),
                ('Transcript_name', models.TextField(blank=True, default=b'-', null=True)),
                ('Chromosome', models.TextField(blank=True, default=b'-', null=True)),
                ('Transcript_start', models.TextField(blank=True, default=b'-', null=True)),
                ('Transcript_end', models.TextField(blank=True, default=b'-', null=True)),
                ('Strand', models.TextField(blank=True, default=b'-', null=True)),
                ('Start_codon', models.TextField(blank=True, default=b'-', null=True)),
                ('UpstreamATG', models.TextField(blank=True, default=b'-', null=True)),
                ('Protein_function', models.TextField(blank=True, default=b'-', null=True)),
                ('UniprotSwissprotID', models.TextField(blank=True, default=b'-', null=True)),
                ('PDB_ID', models.TextField(blank=True, default=b'-', null=True)),
                ('Biological_process', models.TextField(blank=True, default=b'-', null=True)),
                ('Cellular_component', models.TextField(blank=True, default=b'-', null=True)),
                ('Molecular_function', models.TextField(blank=True, default=b'-', null=True)),
            ],
        ),
    ]
