# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 20:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UGP', '0018_eukaryotestablenew2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EukaryotesTableNew1',
        ),
    ]
