# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-01 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UGP', '0019_delete_eukaryotestablenew1'),
    ]

    operations = [
        migrations.AddField(
            model_name='bacteriatablenew1',
            name='TaxaID',
            field=models.TextField(blank=True, default=b'-', null=True),
        ),
    ]
