# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-01 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UGP', '0020_bacteriatablenew1_taxaid'),
    ]

    operations = [
        migrations.AddField(
            model_name='archaeatablenew1',
            name='TaxaID',
            field=models.TextField(blank=True, default=b'-', null=True),
        ),
    ]
